version: '3.9'

services:
  backend:
    image: docker_compose_homework
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - 8000
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/backend/static
      - media_volume:/home/app/backend/media
    env_file:
      - ./.env.prod
    depends_on:
      - database
  database:
    image: postgres:14.6-alpine
    env_file:
      - ./.env.db
    volumes:
      - pg-data:/var/lib/postgres/data
  server:
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "2345:80"
    depends_on:
      - backend
volumes:
    pg-data:
    static_volume:
    media_volume: